controllers_security:
    resource: ../../src/Controller/Security
    type: annotation

controllers_admin:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: /admin
    name_prefix: admin_

controllers_front:
    resource: ../../src/Controller/Front
    type: annotation
    name_prefix: front_

kernel:
    resource: ../../src/Kernel.php
    type: annotation
